import Head from 'next/head'
import { useState } from 'react'

import styles from './Home.module.scss'
import Sidebar from '@/components/sidebar'
import Logo from '@/components/logo'
import Map from '@/components/map'

import { MapModel } from '@/model/map'
import { usePersistentState } from '@/model/state'

const defaultMap: MapModel = {
  name: "Faerun",
  imageUrl: "http://media.wizards.com/2015/images/dnd/resources/Sword-Coast-Map_LowRes.jpg",
  layers: [
    {
      id: 0,
      name: "Towns",
      iconUrl: "https://cdn.pixabay.com/photo/2019/09/12/13/40/house-4471626_960_720.png",
      areas: [],
    },
  ],
  points: [
    {
      name: 'Waterdeep',
      description: 'The city of splendor!',
      x: 50,
      y: 50,
      layerIds: [0],
    },
  ],
}

export default function Home() {
  const [map, setMap] = usePersistentState('map', defaultMap)
  const [visibleLayers, setVisibleLayers] = useState<number[]>([0])

  return (
    <>
      <Head>
        <title>World Canvas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ico.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar />
        <Map map={defaultMap} visibleLayers={visibleLayers} />
        <Logo />
      </main>
    </>
  )
}
